name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t nettrs .
    - name: Execute Docker Container
      run: docker run -it -d --rm -v $PWD:/work --name nettrs nettrs
    - name: Generate Makefile inside Docker Container
      run: docker exec nettrs cmake ..
    - name: Build nettrs inside Docker Container
      run: docker exec nettrs make
